### ISSUE TITLE
Not enough swag

### ISSUE THREAD

**Issue by yrsegal** [SticksandStones/SticksandStones#1]
This is a breaking bug

**Comment by TheDoctorSoda** [comment]
@Blorph you need to add the gamebreaking bug flair!!

**Comment by Prospector** [comment]
We'll get on this ASAP

**Comment by Prospector** [comment]
Hopefully the fix I just pushed fixes your issue. I wasn't able to reproduce it, but I think I found what was causing it. Let me know if the bug's fixed, when you have a chance!
